# Generated by Django 4.1.2 on 2022-10-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_type",
            field=models.CharField(
                choices=[("LG", "Light"), ("NM", "Normal"), ("HV", "Heavy")],
                max_length=2,
            ),
        ),
    ]
