# Generated by Django 4.1.2 on 2022-10-11 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_car_car_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartype",
            name="type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to="api.car",
            ),
        ),
    ]
