# Generated by Django 4.1.2 on 2022-10-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_cartype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartype",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to="api.car",
            ),
        ),
    ]
