# Generated by Django 4.1.2 on 2022-10-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_cartype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_type",
            field=models.CharField(
                choices=[("Light", "Light"), ("Normal", "Normal"), ("Heavy", "Heavy")],
                max_length=10,
            ),
        ),
    ]
